/**
 * Name        : com.malcolm.daotest.mybatis.model.Designation.java
 * Author      : Malcolm
 * Created on  : May 22, 2014
 *
 * Description : Generated by MyBatis generator please check /src/main/resources/generatorConfig.xml
 */
package com.malcolm.daotest.mybatis.model;

/**
 * Generated by MyBatis generator please check /src/main/resources/generatorConfig.xml
 * 
 * @author Malcolm
 */
public class Designation {
    private Integer designation_id;

    private String designation_name;
    
    private String designation_desc;

    public Integer getDesignation_id() {
        return designation_id;
    }

    public void setDesignation_id(Integer designation_id) {
        this.designation_id = designation_id;
    }

    public String getDesignation_name() {
        return designation_name;
    }

    public void setDesignation_name(String designation_name) {
        this.designation_name = designation_name;
    }

	/**
	 * @return the designation_desc
	 */
	public String getDesignation_desc() {
		return designation_desc;
	}

	/**
	 * @param designation_desc the designation_desc to set
	 */
	public void setDesignation_desc(String designation_desc) {
		this.designation_desc = designation_desc;
	}
}