/**
 * Name        : com.malcolm.daotest.mybatis.model.Employee.java
 * Author      : Malcolm
 * Created on  : May 22, 2014
 *
 * Description : Generated by MyBatis generator please check /src/main/resources/generatorConfig.xml
 */
package com.malcolm.daotest.mybatis.model;

import java.sql.Timestamp;
import java.util.List;

/**
 * Generated by MyBatis generator please check /src/main/resources/generatorConfig.xml
 * Additional updates are made to add Employee-Role and Employee-Project Association 
 * 
 * @author Malcolm
 */
public class Employee {
    private Integer emp_id;

    private String emp_first_name;

    private String emp_last_name;

    private Timestamp emp_start_date;

    private Timestamp emp_end_date;

    private Integer designation_id;

    private Designation designation;
    
    private Integer dept_id;
    
    private Department department;

    private Integer mgr_id;
    
    private Employee manager;

    private String update_user;

    private Timestamp update_date;
    
    private List<RoleEmployee> employeeRoleAssn;
    
    private List<ProjectEmployee> employeeProjectAssn;

    public Integer getEmp_id() {
        return emp_id;
    }

    public void setEmp_id(Integer emp_id) {
        this.emp_id = emp_id;
    }

    public String getEmp_first_name() {
        return emp_first_name;
    }

    public void setEmp_first_name(String emp_first_name) {
        this.emp_first_name = emp_first_name;
    }

    public String getEmp_last_name() {
        return emp_last_name;
    }

    public void setEmp_last_name(String emp_last_name) {
        this.emp_last_name = emp_last_name;
    }

    public Timestamp getEmp_start_date() {
        return emp_start_date;
    }

    public void setEmp_start_date(Timestamp emp_start_date) {
        this.emp_start_date = emp_start_date;
    }

    public Timestamp getEmp_end_date() {
        return emp_end_date;
    }

    public void setEmp_end_date(Timestamp emp_end_date) {
        this.emp_end_date = emp_end_date;
    }

    public Integer getDesignation_id() {
        return designation_id;
    }

    public void setDesignation_id(Integer designation_id) {
        this.designation_id = designation_id;
    }

    public Integer getDept_id() {
        return dept_id;
    }

    public void setDept_id(Integer dept_id) {
        this.dept_id = dept_id;
    }

    public Integer getMgr_id() {
        return mgr_id;
    }

    public void setMgr_id(Integer mgr_id) {
        this.mgr_id = mgr_id;
    }

    public String getUpdate_user() {
        return update_user;
    }

    public void setUpdate_user(String update_user) {
        this.update_user = update_user;
    }

    public Timestamp getUpdate_date() {
        return update_date;
    }

    public void setUpdate_date(Timestamp update_date) {
        this.update_date = update_date;
    }

	/**
	 * @return the employeeRoleAssn
	 */
	public List<RoleEmployee> getEmployeeRoleAssn() {
		return employeeRoleAssn;
	}

	/**
	 * @param employeeRoleAssn the employeeRoleAssn to set
	 */
	public void setEmployeeRoleAssn(List<RoleEmployee> employeeRoleAssn) {
		this.employeeRoleAssn = employeeRoleAssn;
	}

	/**
	 * @return the employeeProjectAssn
	 */
	public List<ProjectEmployee> getEmployeeProjectAssn() {
		return employeeProjectAssn;
	}

	/**
	 * @param employeeProjectAssn the employeeProjectAssn to set
	 */
	public void setEmployeeProjectAssn(List<ProjectEmployee> employeeProjectAssn) {
		this.employeeProjectAssn = employeeProjectAssn;
	}

	/**
	 * @return the department
	 */
	public Department getDepartment() {
		return department;
	}

	/**
	 * @param department the department to set
	 */
	public void setDepartment(Department department) {
		this.department = department;
	}

	/**
	 * @return the manager
	 */
	public Employee getManager() {
		return manager;
	}

	/**
	 * @param manager the manager to set
	 */
	public void setManager(Employee manager) {
		this.manager = manager;
	}

	/**
	 * @return the designation
	 */
	public Designation getDesignation() {
		return designation;
	}

	/**
	 * @param designation the designation to set
	 */
	public void setDesignation(Designation designation) {
		this.designation = designation;
	}
}