/**
 * Name        : com.malcolm.daotest.mybatis.model.Project.java
 * Author      : Malcolm
 * Created on  : May 22, 2014
 *
 * Description : Generated by MyBatis generator please check /src/main/resources/generatorConfig.xml
 */
package com.malcolm.daotest.mybatis.model;

import java.sql.Timestamp;

/**
 * Generated by MyBatis generator please check /src/main/resources/generatorConfig.xml
 * 
 * @author Malcolm
 */
public class Project {
    private Integer project_id;

    private String project_name;

    private String project_desc;

    private Integer project_manager;
    
    private Employee manager;

    private Timestamp project_startdate;

    private Timestamp project_enddate;

    private String update_user;

    private Timestamp update_date;

    public Integer getProject_id() {
        return project_id;
    }

    public void setProject_id(Integer project_id) {
        this.project_id = project_id;
    }

    public String getProject_name() {
        return project_name;
    }

    public void setProject_name(String project_name) {
        this.project_name = project_name;
    }

    public String getProject_desc() {
        return project_desc;
    }

    public void setProject_desc(String project_desc) {
        this.project_desc = project_desc;
    }

    public Integer getProject_manager() {
        return project_manager;
    }

    public void setProject_manager(Integer project_manager) {
        this.project_manager = project_manager;
    }

    public Timestamp getProject_startdate() {
        return project_startdate;
    }

    public void setProject_startdate(Timestamp project_startdate) {
        this.project_startdate = project_startdate;
    }

    public Timestamp getProject_enddate() {
        return project_enddate;
    }

    public void setProject_enddate(Timestamp project_enddate) {
        this.project_enddate = project_enddate;
    }

    public String getUpdate_user() {
        return update_user;
    }

    public void setUpdate_user(String update_user) {
        this.update_user = update_user;
    }

    public Timestamp getUpdate_date() {
        return update_date;
    }

    public void setUpdate_date(Timestamp update_date) {
        this.update_date = update_date;
    }

	/**
	 * @return the manager
	 */
	public Employee getManager() {
		return manager;
	}

	/**
	 * @param manager the manager to set
	 */
	public void setManager(Employee manager) {
		this.manager = manager;
	}
}