/**
 * Name        : com.malcolm.daotest.mybatis.mapper.DesignationMapper.java
 * Author      : Malcolm
 * Created on  : May 22, 2014
 *
 * Description : Generated by MyBatis generator please check /src/main/resources/generatorConfig.xml
 */
package com.malcolm.daotest.mybatis.mapper;

import com.malcolm.daotest.mybatis.model.Designation;

/**
 * Generated by MyBatis generator please check /src/main/resources/generatorConfig.xml
 * 
 * @author Malcolm
 */
public interface DesignationMapper {
    int deleteByPrimaryKey(Integer designation_id);

    int insert(Designation record);

    int insertSelective(Designation record);

    Designation selectByPrimaryKey(Integer designation_id);

    int updateByPrimaryKeySelective(Designation record);

    int updateByPrimaryKey(Designation record);
}