/**
 * Name        : com.malcolm.daotest.mybatis.mapper.ProjectEmployeeMapper.java
 * Author      : Malcolm
 * Created on  : May 22, 2014
 *
 * Description : Generated by MyBatis generator please check /src/main/resources/generatorConfig.xml
 */
package com.malcolm.daotest.mybatis.mapper;

import com.malcolm.daotest.mybatis.model.ProjectEmployee;

/**
 * Generated by MyBatis generator please check /src/main/resources/generatorConfig.xml
 * 
 * @author Malcolm
 */
public interface ProjectEmployeeMapper {
    int deleteByPrimaryKey(Integer project_emp_assn_id);

    int insert(ProjectEmployee record);

    int insertSelective(ProjectEmployee record);

    ProjectEmployee selectByPrimaryKey(Integer project_emp_assn_id);

    int updateByPrimaryKeySelective(ProjectEmployee record);

    int updateByPrimaryKey(ProjectEmployee record);
}