/**
 * Name        : com.malcolm.daotest.mybatis.mapper.ProjectMapper.java
 * Author      : Malcolm
 * Created on  : May 22, 2014
 *
 * Description : Generated by MyBatis generator please check /src/main/resources/generatorConfig.xml
 */
package com.malcolm.daotest.mybatis.mapper;

import com.malcolm.daotest.mybatis.model.Project;

/**
 * Generated by MyBatis generator please check /src/main/resources/generatorConfig.xml
 * 
 * @author Malcolm
 */
public interface ProjectMapper {
    int deleteByPrimaryKey(Integer project_id);

    int insert(Project record);

    int insertSelective(Project record);

    Project selectByPrimaryKey(Integer project_id);

    int updateByPrimaryKeySelective(Project record);

    int updateByPrimaryKey(Project record);
}