/**
 * Name        : com.malcolm.daotest.mybatis.mapper.RoleEmployeeMapper.java
 * Author      : Malcolm
 * Created on  : May 22, 2014
 *
 * Description : Generated by MyBatis generator please check /src/main/resources/generatorConfig.xml
 */
package com.malcolm.daotest.mybatis.mapper;

import com.malcolm.daotest.mybatis.model.RoleEmployee;

/**
 * Generated by MyBatis generator please check /src/main/resources/generatorConfig.xml
 * 
 * @author Malcolm
 */
public interface RoleEmployeeMapper {
    int deleteByPrimaryKey(Integer role_emp_assn_id);

    int insert(RoleEmployee record);

    int insertSelective(RoleEmployee record);

    RoleEmployee selectByPrimaryKey(Integer role_emp_assn_id);

    int updateByPrimaryKeySelective(RoleEmployee record);

    int updateByPrimaryKey(RoleEmployee record);
}